#!/bin/sh
set -e
# Automatically added by dh_installdocs
if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/musepack-decoder-i386 ]; then
	rm -f /usr/doc/musepack-decoder-i386
fi
# End automatically added section
