#!/bin/sh
set -e
# Automatically added by dh_installdocs
if [ "$1" = "configure" ]; then
	if [ -d /usr/doc -a ! -e /usr/doc/musepack-encoder-i386 -a -d /usr/share/doc/musepack-encoder-i386 ]; then
		ln -sf ../share/doc/musepack-encoder-i386 /usr/doc/musepack-encoder-i386
	fi
fi
# End automatically added section
